### ISSUE TITLE
Installing `nvidia-mig-parted` fails.

### ISSUE THREAD

**Issue by mam10eks** [NVIDIA/mig-parted#10]
Dear all,

thank you for your work!
We used the following installation instructions to build `nvidia-mig-parted`:

```
docker run \
    -v $(pwd):/dest \
    golang:1.15 \
    sh -c "
    GO111MODULE=off go get -u github.com/NVIDIA/mig-parted/cmd/nvidia-mig-parted
    GOBIN=/dest     go install github.com/NVIDIA/mig-parted/cmd/nvidia-mig-parted
    "
```

I think that exactly this statement worked fine a few weeks ago, but currently it fails with:

```
src/github.com/NVIDIA/mig-parted/cmd/util/util.go:100:18: undefined: os.ReadFile
```

Is this a known problem or did I made some mistake? (I tested it on multiple locations, the error was always the `os.ReadFile` one from above.)

Best regards,

Maik

**Comment by klueska** [comment]
Yeah we updated the code for go 1.16 but missed updating this script (most people install via one of the packages provided on our release page where everything is built properly).

This commit (in a pending MR) should fix the issue. I expect it to be merged by end of day tomorrow.

https://gitlab.com/nvidia/cloud-native/mig-parted/-/merge_requests/93/diffs?commit_id=75d61057ffdab1110ebdea18813798b23a4fb1e3

**Comment by mam10eks** [comment]
Ah, cool, thank you very much for the fast response.

With the changes in the commit above everything works :)
