### ISSUE TITLE
[BUG] The default value for mig-enabled should be false.

### ISSUE THREAD

**Issue by ZhengXinwei-F** [NVIDIA/mig-parted#129]
When using `nvidia-mig-parted` for partial GPU MIG configuration, I didn't set `mig-enabled` to false for the GPUs that were not intended for MIG. For example:
```
  4-7-balanced:
    - devices: [4,5,6,7]
      mig-enabled: true
      mig-devices:
        "1g.10gb": 2
        "2g.20gb": 1
        "3g.40gb": 1

```

That cause GPUs 0-3 were enabled for MIG, which was not my intention. It would be more appropriate for false to be the default value in the configuration specifications. If the intention of community is to have MIG enabled by default, it should be renamed to mig-disabled.

Therefore, my configuration need to modified to:
```
  4-7-balanced:
    - devices: [0,1,2,3]
      mig-enabled: false
    - devices: [4,5,6,7]
      mig-enabled: true
      mig-devices:
        "1g.10gb": 2
        "2g.20gb": 1
        "3g.40gb": 1
```

**Comment by klueska** [comment]
This is not something we plan to do. It is not required to change the settings on all GPUs at once. You must specify which ones you want changed (either with `all` or listing them explicitly). If you do not list them, their settings do not change.
