### ISSUE TITLE
Issue when installing the systemd install.sh script

### ISSUE THREAD

**Issue by ishackigozi** [NVIDIA/mig-parted#15]
Hello Support,
I am having some issues with the Systemd installation script. When I run the install.sh script, I get this error. 

(base) root@mpigpu06dal:/opt/mig-parted/deployments/systemd# ./install.sh
Unable to find image 'golang:1.16.4' locally
1.16.4: Pulling from library/golang
d960726af2be: Pull complete
e8d62473a22d: Pull complete
8962bc0fad55: Pull complete
65d943ee54c1: Pull complete
f2253e6fbefa: Pull complete
6d7fa7c7d5d3: Pull complete
e2e442f7f89f: Pull complete
Digest: sha256:8a106c4b4005efb43c0ba4bb5763b84742c7e222bad5a8dff73cc9f7710c64ee
Status: Downloaded newer image for golang:1.16.4
go: downloading github.com/NVIDIA/mig-parted v0.5.0
go install github.com/NVIDIA/mig-parted/cmd@latest: github.com/NVIDIA/mig-parted@v0.5.0: verifying module: github.com/NVIDIA/mig-parted@v0.5.0: Get "https://sum.golang.org/lookup/github.com/!n!v!i!d!i!a/mig-parted@v0.5.0": read tcp 172.17.0.2:53664->34.64.4.81:443: read: connection reset by peer
**mv: cannot stat '/go/bin/cmd': No such file or directory**

Where is the /go/bin/cmd

**Comment by elezar** [comment]
The issue is that the `go install` line is failing due to a network error and this means that no files are generated at `/go/bin/cmd` in the container being run. This triggers the last error message you're seeing.

Could this have been a transient error?

**Comment by ishackigozi** [comment]
Hello Elezar,
Our servers dont have internet access. Do you by any chance know what url's need to be unblocked?

**Comment by klueska** [comment]
If you're not required to build it yourself, note that `deb`, `rpm`, and `tar` based packages are included here for every release: https://github.com/NVIDIA/mig-parted/releases/tag/v0.5.0

**Comment by klueska** [comment]
Can this issue be closed?

**Comment by ishackigozi** [comment]
Yes please. Go ahead and close the case.

**Comment by ishackigozi** [comment]
Thank you all for the assistance.
