### ISSUE TITLE
How to do mig on a gpu

### ISSUE THREAD

**Issue by mayooot** [NVIDIA/mig-parted#44]
My environment has 8 A100 GPU and now I'm trying to use mig on gpu number 7, but it doesn't work.
~~~ shell
cat <<EOF | nvidia-mig-parted apply -f -
version: v1
mig-configs:
  all-1g.5gb:
  - devices: 7
    mig-enabled: true
    mig-devices:
      1g.5gb: 7
EOF
~~~

Error:
~~~
FATA[0000] Error parsing config file: unmarshal error: error unmarshaling JSON: while decoding JSON: invalid string input for 'devices': 7
~~~

What should I do? [mig-parted](https://github.com/NVIDIA/mig-parted) only support operations on all gpus?

**Comment by klueska** [comment]
`devices` either takes the keyword `all` or a list of devices indices. so you would want:
```
cat <<EOF | nvidia-mig-parted apply -f -
version: v1
mig-configs:
  all-1g.5gb:
  - devices: [7]
    mig-enabled: true
    mig-devices:
      1g.5gb: 7
EOF
```

**Comment by mayooot** [comment]
> `devices` either takes the keyword `all` or a list of devices indices. so you would want:
> 
> ```
> cat <<EOF | nvidia-mig-parted apply -f -
> version: v1
> mig-configs:
>   all-1g.5gb:
>   - devices: [7]
>     mig-enabled: true
>     mig-devices:
>       1g.5gb: 7
> EOF
> ```

This looks great. Thanks
