### ISSUE TITLE
A start job for Configure MIG on NVIDIA GPUs (x min x sec / no limit)

### ISSUE THREAD

**Issue by dogtown63** [NVIDIA/mig-parted#8]
Hi. i deployed
 nvidia-mig-manager.service - everything is ok! But after the restart I see the message: "A start job for Configure MIG on NVIDIA GPUs (x min x sec / no limit)" - is this normal? How can I get rid of this?
![nvidia](https://user-images.githubusercontent.com/89972965/160444823-7e441a77-d9ef-4ae5-b988-b955aa85a894.PNG)

**Comment by mariorosati** [comment]
I also observe the same behavior. It's normal?
